// Training set
var data = 
    [{class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
     {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-44', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right-up', irradiat: 'no'},
     {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
     {class: 'no-recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left-up', irradiat: 'no'},
     {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '0-4', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right-low', irradiat: 'no'},
     {class: 'no-recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
     {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
     {class: 'no-recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
     {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '50-54', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
     
     //carlaino e mylena
     
     
     
     
     {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '0-4', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'lt40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'lt40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_up', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '25-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '0-4', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '5-9', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '50-54', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_low', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '50-59', menopause: 'lt40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '70-79', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '70-79', menopause: 'ge40', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '70-79', menopause: 'ge40', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '0-4', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '5-9', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '0-4', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '20-29', menopause: 'premeno', tumorsize: '30-39', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '30-39', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '50-54', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '5-9', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'central', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '70-79', menopause: 'ge40', tumorsize: '0-4', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '0-4', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '40-49', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_up', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'right_low', irradiat: 'no'},

    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '70-79', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '30-34', invnodes: '6-8', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '25-29', invnodes: '6-8', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '35-39', invnodes: '9-11', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},

    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '35-39', invnodes: '9-11', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'right_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '40-44', invnodes: '3-5', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '6-8', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '40-44', invnodes: '3-5', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'right_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '5-9', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '40-44', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '45-49', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '45-49', invnodes: '6-8', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: '?', degmalig: 2, breast: 'left', breastquad: 'right_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '50-54', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '30-34', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'lt40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '25-29', invnodes: '15-17', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '30-34', invnodes: '3-5', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '35-39', invnodes: '15-17', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'lt40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '40-44', invnodes: '3-5', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '25-29', invnodes: '3-5', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'central', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'right',  breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '25-29', invnodes: '3-5', nodecaps: '?', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '25-29', invnodes: '3-5', nodecaps: '?', degmalig: 1, breast: 'right', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'ge40', tumorsize: '40-44', invnodes: '15-17', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '30-34', invnodes: '6-8', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'ge40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '3-5', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad:'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '30-34', invnodes: '9-11', nodecaps: '?', degmalig: 3, breast: 'left', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '30-34', invnodes: '9-11', nodecaps: '?', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '6-8', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '15-19', invnodes: '12-14', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'right_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '30-34', invnodes: '6-8', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'right_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '50-54', invnodes: '0-2', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '10-14', invnodes: '3-5', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '10-14', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'central', irradiat:  'yes'},
    {class: 'no-recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'no-recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no',  degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'right_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '0-4', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'central', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: '?', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'right_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'right_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'central', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'central', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'right_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'right_low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '25-29', invnodes: '3-5', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '40-49', menopause: 'ge40', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '15-17', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '40-44', invnodes: '3-5', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '45-49', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'right_up', irradiat: 'yes'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '50-54', invnodes: '9-11', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '3-5', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '30-34', invnodes: '3-5', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'recurrence-events', age: '70-79', menopause: 'ge40', tumorsize: '15-19', invnodes: '9-11', nodecaps: '?', degmalig: 1, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '60-69', menopause: 'ge40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '3-5', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left_low', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'left_up', irradiat: 'yes'},
     
     
     
     
     
     //
     
     {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '15-19', invnodes: '15-17', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'get40', tumorsize: '25-29', invnodes: '6-8', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '50-59', menopause: 'get40', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'right_up', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '12-14', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left-up', irradiat: 'yes'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '30-34', invnodes: '9-11', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left-up', irradiat: 'yes'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '15-19', invnodes: '6-8', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '50-59', menopause: 'get40', tumorsize: '30-34', invnodes: '9-11', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'right-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '35-39', invnodes: '6-8', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
    {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '50-54', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '30-34', menopause: 'premeno', tumorsize: '40-44', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '50-54', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'right-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'left', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-24', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '50-59', menopause: 'get40', tumorsize: '30-34', invnodes: '6-8', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'right-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '25-29', invnodes: '3-5', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'get40', tumorsize: '25-29', invnodes: '12-14', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'right-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'lt40', tumorsize: '20-24', invnodes: '0-2', nodecaps: '?', degmalig: 1, breast: 'left', breastquad: 'left-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'lt40', tumorsize: '20-24', invnodes: '0-2', nodecaps: '?', degmalig: 1, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '35-39', invnodes: '9-11', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '30-34', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'right-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '20-24', invnodes: '24-26', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '35-39', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '50-59', menopause: 'get40', tumorsize: '30-34', invnodes: '6-8', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'right-low', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '25-29', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'right', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '15-19', invnodes: '0-2', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'left-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'yes', degmalig: 2, breast: 'right', breastquad: 'right_up', irradiat: 'yes'},
    {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '30-34', invnodes: '3-5', nodecaps: 'yes', degmalig: 2, breast: 'left', breastquad: 'central', irradiat: 'yes'},
    {class: 'recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '25-29', invnodes: '9-11', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'left-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '25-29', invnodes: '6-8', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'right-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '10-14', invnodes: '6-8', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left-up', irradiat: 'yes'},
    {class: 'recurrence-events', age: '50-59', menopause: 'premeno', tumorsize: '35-39', invnodes: '15-17', nodecaps: 'yes', degmalig: 3, breast: 'right', breastquad: 'right-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'get40', tumorsize: '40-44', invnodes: '6-8', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '50-59', menopause: 'get40', tumorsize: '40-44', invnodes: '6-8', nodecaps: 'yes', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'yes'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '30-34', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'left', breastquad: 'left-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '30-39', menopause: 'premeno', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left-up', irradiat: 'yes'},
    {class: 'recurrence-events', age: '60-69', menopause: 'get40', tumorsize: '20-24', invnodes: '0-2', nodecaps: 'no', degmalig: 1, breast: 'right', breastquad: 'left-up', irradiat: 'no'},
    {class: 'recurrence-events', age: '40-49', menopause: 'get40', tumorsize: '30-34', invnodes: '3-5', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'no'},
    {class: 'recurrence-events', age: '50-59', menopause: 'get40', tumorsize: '30-34', invnodes: '3-5', nodecaps: 'no', degmalig: 3, breast: 'left', breastquad: 'left-low', irradiat: 'no'}];
     

// Configuration
var config = {
    trainingSet: data, 
    categoryAttr: 'class'
};

// Building Decision Tree
var decisionTree = new dt.DecisionTree(config);

// Building Random Forest
var numberOfTrees = 3;
var randomForest = new dt.RandomForest(config, numberOfTrees);

// Testing Decision Tree and Random Forest
var comic = {class: 'no-recurrence-events', age: '40-49', menopause: 'premeno', tumorsize: '20-44', invnodes: '0-2', nodecaps: 'no', degmalig: 2, breast: 'right', breastquad: 'right-up', irradiat: 'no'};

var decisionTreePrediction = decisionTree.predict(comic);
var randomForestPrediction = randomForest.predict(comic);

// Displaying predictions
document.getElementById('testingItem').innerHTML = JSON.stringify(comic, null, 0);
document.getElementById('decisionTreePrediction').innerHTML = JSON.stringify(decisionTreePrediction, null, 0);
document.getElementById('randomForestPrediction').innerHTML = JSON.stringify(randomForestPrediction, null, 0);

// Displaying Decision Tree
document.getElementById('displayTree').innerHTML = treeToHtml(decisionTree.root);


// Recursive (DFS) function for displaying inner structure of decision tree
function treeToHtml(tree) {
    // only leafs containing category
    if (tree.category) {
        return  ['<ul>',
                    '<li>',
                        '<a href="#">',
                            '<b>', tree.category, '</b>',
                        '</a>',
                    '</li>',
                 '</ul>'].join('');
    }
    
    return  ['<ul>',
                '<li>',
                    '<a href="#">',
                        '<b>', tree.attribute, ' ', tree.predicateName, ' ', tree.pivot, ' ?</b>',
                    '</a>',
                    '<ul>',
                        '<li>',
                            '<a href="#">yes</a>',
                            treeToHtml(tree.match),
                        '</li>',
                        '<li>', 
                            '<a href="#">no</a>',
                            treeToHtml(tree.notMatch),
                        '</li>',
                    '</ul>',
                '</li>',
             '</ul>'].join('');
}
